Test/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^amovies/',include('amovies.urls',namespace='amovies')),
]

amovies/urls.py
from django.conf.urls import url

from amovies import views

urlpatterns = [
    url(r'^login/',views.login,name='login'),
    url(r'^register/',views.register,name='register'),
    url(r'^dologin/',views.dologin,name='dologin'),
    url(r'^doregister/',views.doregister,name='doregister'),
    url(r'^home/',views.home,name='home'),
    url(r'^userinfo/',views.userinfo,name='userinfo'),
    url(r'^douserinfo/',views.douserinfo,name='douserinfo'),
    url(r'^home_logined/',views.home_logined,name='home_logined'),
    url(r'^home_logined_collected/',views.home_logined_collected,name='home_logined_collected'),
    url(r'^addtomycollect/',views.addtomycollect,name='addtomycollect'),
    url(r'^delmycollect/',views.delmycollect,name='delmycollect'),
]

amovies/models.py
from django.db import models

# Create your models here.
# 用户表
class Users(models.Model):
    u_name = models.CharField(max_length=20)
    u_password = models.CharField(max_length=50)
    u_icons = models.ImageField(upload_to='icons')
    u_email = models.CharField(max_length=50)

    class Meta:
        db_table = "Users"

# 电影表
class Movies(models.Model):
    postid = models.CharField(max_length=20)
    title = models.CharField(max_length=100)
    image = models.CharField(max_length=200)
    duration = models.CharField(max_length=20)
    app_fu_title = models.CharField(max_length=200)

    class Meta:
        db_table = "Movies"

# 收藏表
class MyCollects(models.Model):
    m_users = models.ForeignKey('Users')
    m_movies = models.ForeignKey('Movies')

    class Meta:
        db_table = "MyCollects"

amovies/views.py
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from amovies.models import Users, Movies, MyCollects


def login(request):
    return render(request,'login.html')


def register(request):

    return render(request,'register.html')

def dologin(request):
    username = request.POST.get('username')
    password = request.POST.get('userpassword')
    user = Users.objects.filter(u_name=username)
    if len(user) > 0:
    # 比对用户名 密码
        if user.first().u_password == password:
            request.session['username'] = username
        #     登录成功   跳转回个人中心
            response = HttpResponseRedirect(reverse('amovies:home_logined'))
            return response
        else:
            return redirect(reverse('amovies:login'))

def doregister(request):

    try:
        username = request.POST.get("username")
        usericon = request.FILES["usericon"]
        password = request.POST.get("userpassword")
        email = request.POST.get("useremail")

        u = Users()
        u.u_name = username
        u.u_icons = usericon
        u.u_password = password
        u.u_email = email
        u.save()

        request.session['username'] = username
        return redirect(reverse('amovies:home_logined'))
    except Exception as e:
        print("注册失败")
        return HttpResponse("注册失败")


def home_logined(request):

    username = request.session.get("username")
    if username == None:
        username = "未登录"
        usericon = ''
        is_login = False
    else:
        is_login = True
        user = Users.objects.get(u_name=username)
        # usericon = "http://127.0.0.1:8000/static/uploadfiles/" + user.u_icon.path
        usericon = "http://127.0.0.1:8000/static/uploadfiles/" + user.u_icons.url

        # print(usericon)
    movies = Movies.objects.all()
    context = {
        "username": username,
        "usericon": usericon,
        "movies": movies,
        "is_login": is_login,
    }

    return render(request, 'home_logined.html', context=context)


def userinfo(request):

    username = request.session.get("username")
    uname = Users.objects.get(u_name=username)
    # usericon = uname.u_icons
    usericons = "http://127.0.0.1:8000/static/uploadfiles/" + uname.u_icons.url
    context = {
        "username": username,
        "usericon":usericons,
    }
    return render(request, 'userinfo.html', context=context)


def douserinfo(request):

    username = request.session.get("username")
    uname = Users.objects.get(u_name=username)

    icons = request.FILES['icon']
    email = request.POST.get('email')

    uname.u_icons = icons
    uname.u_email = email

    uname.save()

    return redirect(reverse("amovies:home_logined"))


def home(request):

    movies = Movies.objects.all()
    context = {
        "movies": movies,
    }

    return render(request, 'home.html', context=context)


def home_logined_collected(request):
    # 判断是否登录
    username = request.session.get("username")
    uname = Users.objects.get(u_name=username)
    usericon = "http://127.0.0.1:8000/static/uploadfiles/" + uname.u_icons.url
    print(usericon)
    if username == None:
        return redirect(reverse("amovies:login"))
    user = Users.objects.get(u_name=username)

    # print(type(user))
    mycollects = MyCollects.objects.filter(m_users=user)
    # print(type(mycollects))

    movies = Movies.objects.all()
    context = {
        "mycollects": mycollects,
        "username":username,
        "usericon":usericon,
        "movies":movies,
    }

    return render(request, 'home_logined_collected.html', context=context)


def addtomycollect(request):

    username = request.session.get("username")
    if username == None:
        return JsonResponse({"msg": "您还没有登录不能收藏，请先登录"})
    # 用户已登录
    movie_id = request.GET.get("movieid")
    movies = Movies.objects.get(pk=movie_id)
    # 获取登录用户信息
    user = Users.objects.get(u_name=username)
    # 去数据库中查找
    m = MyCollects.objects.filter(m_users=user).filter(m_movies=movies)
    if len(m) == 0:
        m = MyCollects()
    else:
        m = m.first()

    m.m_users = user
    m.m_movies = movies

    m.save()
    return JsonResponse({"msg": "添加成功"})


def delmycollect(request):
    mycollectid = request.GET.get("mycollectid")

    collect = MyCollects.objects.get(pk=mycollectid)
    collect.delete()

    return JsonResponse({"msg": "删除成功"})

templates/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>未登录</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <script type="text/javascript" src={% static 'amovies/js/jquery.js' %}></script>
    <script type="text/javascript" src={% static 'amovies/js/bootstrap.js' %}></script>
    <link rel="stylesheet" href="{% static 'amovies/css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/bootstrap-theme.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/swiper.css' %}"/>
    <script type="text/javascript" src="{% static 'amovies/js/swiper.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/reset.css' %}"/>

    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/home.css' %}"/>
    <script type="text/javascript" src="{% static 'amovies/js/home.js' %}"></script>
</head>
<body>

<div class="container-fluid">

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'amovies:login' %}">未登录</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <!--<li>
                    <a href="#">注册</a>
                </li>
                <li>
                    <a href="#">登陆</a>
                </li>-->
                <li>

                    <a href="{% url 'amovies:register' %}"><span>注册</span></a>
                </li>

                <li>
                    <a href="{% url 'amovies:login' %}"><span>登录</span></a>
                </li>
            </ul>
        </div>

    </nav>

    <div class="swiper-container">
        <div class="swiper-wrapper">
            {% for movie in movies %}
                <div class="swiper-slide">

                    <img src="{{ movie.image }}" alt="">

                </div>
            {% endfor %}

            {#					<div class="swiper-slide">#}
            {#						<img src="https://cs.vmovier.com/Uploads/Banner/2017/12/18/5a379a0c4bff3.jpg" alt="">#}
            {#					</div>#}
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination swiper-pagination-white"></div>
        <!-- Add Arrows -->
        <div class="swiper-button-next swiper-button-white"></div>
        <div class="swiper-button-prev swiper-button-white"></div>
    </div>

    <ul class="nav nav-tabs child-nav">
        <li role="presentation" class="active">
            <a href="#">最新推荐</a>
        </li>
        <li role="presentation">
            <a href="#">收藏</a>
        </li>

    </ul>


    <ul class="movie_list">
        {% for movie in movies %}
            <li>
            <div class="movie_list_left">
                <a target="_blank" href="http://app.vmoiver.com/{{movie.postid}}?qingapp=app_new" title="{{ movie.title }}">
                    <img src="{{ movie.image }}"
                         alt="超酷一镜到底创意倒放MV《串烧2017》">
                    <div class="bottom-cover">
                        <span class="film-time">{{ movie.duration }}</span>
                    </div>
                </a>
            </div>

            <div class="movie_list_right">
                <h2>
                    <a target="_blank" href="http://app.vmoiver.com/{{movie.postid}}?qingapp=app_new" title="超酷一镜到底创意倒放MV《串烧2017》">
                        <span>{{ movie.app_fu_title }}</span>
                    </a>
                </h2>

                <div class="movie-intro">
                    {{ movie.app_fu_title }}
                </div>
                <div class="movie-like">
                    <span class="glyphicon glyphicon-heart" style="color: red;"></span>
                    <span>200</span>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

templates/home_logined.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人主页</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <script type="text/javascript" src={% static 'amovies/js/jquery.js' %}></script>
    <script type="text/javascript" src={% static 'amovies/js/bootstrap.js' %}></script>
    <link rel="stylesheet" href="{% static 'amovies/css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/bootstrap-theme.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/swiper.css' %}"/>
    <script type="text/javascript" src="{% static 'amovies/js/swiper.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/reset.css' %}"/>

    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/home.css' %}"/>
    <script type="text/javascript" src="{% static 'amovies/js/home.js' %}"></script>
    <script type="text/javascript" src="{% static 'amovies/js/collects.js' %}"></script>

</head>
<body>

<div class="container-fluid">

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'amovies:userinfo' %}">{{ username }}</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <!--<li>
                    <a href="#">注册</a>
                </li>
                <li>
                    <a href="#">登陆</a>
                </li>-->
                <li>
                    <a class="icon" href="#">
                        <img width="40" height="40" class="img-circle" alt="" src="{{ usericon }}"/>
                    </a>
                </li>

                <li>
                    <a href="{% url 'amovies:userinfo' %}"><span>{{ username }}</span></a>
                </li>
            </ul>
        </div>

    </nav>

    <div class="swiper-container">
        <div class="swiper-wrapper">
            {% for movie in movies %}
                <div class="swiper-slide">

                    <img src="{{ movie.image }}" alt="">

                </div>
            {% endfor %}

            {#					<div class="swiper-slide">#}
            {#						<img src="https://cs.vmovier.com/Uploads/Banner/2017/12/18/5a379a0c4bff3.jpg" alt="">#}
            {#					</div>#}
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination swiper-pagination-white"></div>
        <!-- Add Arrows -->
        <div class="swiper-button-next swiper-button-white"></div>
        <div class="swiper-button-prev swiper-button-white"></div>
    </div>

    <ul class="nav nav-tabs child-nav">
        <li role="presentation" class="active">
            <a href="#">最新推荐</a>
        </li>
        <li role="presentation">
            <a href="{% url 'amovies:home_logined_collected' %}">收藏</a>
        </li>

    </ul>


    <ul class="movie_list">
        {% for movie in movies %}
            <li>
                <div class="movie_list_left">
                    <a target="_blank" href="http://app.vmoiver.com/{{ movie.postid }}?qingapp=app_new"
                       title="{{ movie.title }}">
                        <img src="{{ movie.image }}"
                             alt="超酷一镜到底创意倒放MV《串烧2017》">
                        <div class="bottom-cover">
                            <span class="film-time">{{ movie.duration }}</span>
                        </div>
                    </a>
                </div>

                <div class="movie_list_right">
                    <h2>
                        <a target="_blank" href="http://app.vmoiver.com/{{ movie.postid }}?qingapp=app_new"
                           title="超酷一镜到底创意倒放MV《串烧2017》">
                            <span>{{ movie.app_fu_title }}</span>
                        </a>
                    </h2>

                    <div class="movie-intro">
                        {{ movie.app_fu_title }}
                    </div>
                    <div class="movie-like">
                        <span class="glyphicon glyphicon-heart" style="color: red;"></span>
                        <span class="movies_add" movie_id="{{ movie.id }}">收藏</span>
                    </div>
                </div>
            </li>
        {% endfor %}

    </ul>

</div>
</body>
</html>

templates/home_logined_collected.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的收藏列表</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <script type="text/javascript" src={% static 'amovies/js/jquery.js' %}></script>
    <script type="text/javascript" src={% static 'amovies/js/bootstrap.js' %}></script>
    <link rel="stylesheet" href="{% static 'amovies/css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/bootstrap-theme.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/swiper.css' %}"/>
    <script type="text/javascript" src="{% static 'amovies/js/swiper.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/reset.css' %}"/>

    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/home.css' %}"/>
    <script type="text/javascript" src="{% static 'amovies/js/home.js' %}"></script>
    <script type="text/javascript" src="{% static 'amovies/js/collects.js' %}"></script>
</head>
<body>

<div class="container-fluid">

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'amovies:userinfo' %}">{{ username }}</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li>

                    <a class="icon" href="#">
                        <img width="40" height="40" class="img-circle" alt="" src="{{ usericon }}" />
                    </a>
                </li>

                <li>
                    <a href="{% url 'amovies:userinfo' %}"><span>{{ username }}</span></a>
                </li>
            </ul>
        </div>

    </nav>

    <div class="swiper-container">
        <div class="swiper-wrapper">
            {% for movie in movies %}
                <div class="swiper-slide">

                    <img src="{{ movie.image }}" alt="">

                </div>
            {% endfor %}

            {#					<div class="swiper-slide">#}
            {#						<img src="https://cs.vmovier.com/Uploads/Banner/2017/12/18/5a379a0c4bff3.jpg" alt="">#}
            {#					</div>#}
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination swiper-pagination-white"></div>
        <!-- Add Arrows -->
        <div class="swiper-button-next swiper-button-white"></div>
        <div class="swiper-button-prev swiper-button-white"></div>
    </div>

    <ul class="nav nav-tabs child-nav">
{#        <li role="presentation" class="active">#}
{#            <a href="{% url 'amovies:home_logined' %}">最新推荐</a>#}
{#        </li>#}
        <li role="presentation">
            <a href="#">收藏</a>
        </li>

    </ul>


    <ul class="movie_list">
        {% for mycollect in mycollects %}
            <li>
            <div class="movie_list_left">
                <a target="_blank" href="http://app.vmoiver.com/{{mycollect.m_movies.postid}}?qingapp=app_new" title="{{ mycollect.m_movies.title }}">
                    <img src="{{ mycollect.m_movies.image }}"
                         alt="超酷一镜到底创意倒放MV《串烧2017》">
                    <div class="bottom-cover">
                        <span class="film-time">{{ mycollect.m_movies.duration }}</span>
                    </div>
                </a>
            </div>

            <div class="movie_list_right">
                <h2>
                    <a target="_blank" href="http://app.vmoiver.com/{{mycollect.m_movies.postid}}?qingapp=app_new" title="超酷一镜到底创意倒放MV《串烧2017》">
                        <span>{{ mycollect.m_movies.app_fu_title }}</span>
                    </a>
                </h2>

                <div class="movie-intro">
                    {{ mycollect.m_movies.app_fu_title }}
                </div>
                <div class="movie-like">
                    <span class="glyphicon glyphicon-heart" style="color: red;"></span>
                    <span class="movies_del" mycollectid="{{ mycollect.id }}">取消收藏</span>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

</body>
</html>

templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <script type="text/javascript" src={% static 'amovies/js/jquery.js' %}></script>
    <script type="text/javascript" src={% static 'amovies/js/bootstrap.js' %}></script>
    <link rel="stylesheet" href="{% static 'amovies/css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/bootstrap-theme.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/swiper.css' %}"/>
    <script type="text/javascript" src="{% static 'amovies/js/swiper.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/reset.css' %}"/>
</head>
<body>

<form action="{% url 'amovies:dologin' %}" method="post">
    {% csrf_token %}
    <div class="container-fluid">
			<div class="form-info">
				<form>
					<div class="form-group">
						<label for="exampleInputEmail1">用户名</label>
						<input type="text" name="username" class="form-control" placeholder="请输入用户名">
						<p class="help-block">请输入6-16位用户名</p>
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">密码</label>
						<input type="password" name="userpassword" class="form-control" placeholder="请输入密码">
						<p class="help-block">请输入6位以上拼音字母组合密码</p>
					</div>

					<div class="submit"><button type="submit" class="btn btn-primary">登录</button></div>

				</form>
			</div>
    </div>
{#    <span>用户名:</span><input type="text" name="username">#}
{#    <br>#}
{#    <span>密码:</span><input type="password" name="password">#}
{#    <br>#}
{#    <input type="submit" value="登录">#}
</form>

</body>
</html>

templates/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <script type="text/javascript" src={% static 'amovies/js/jquery.js' %}></script>
    <script type="text/javascript" src={% static 'amovies/js/bootstrap.js' %}></script>
    <link rel="stylesheet" href="{% static 'amovies/css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/bootstrap-theme.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/swiper.css' %}"/>
    <script type="text/javascript" src="{% static 'amovies/js/swiper.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/reset.css' %}"/>
</head>
<body>

<form action="{% url 'amovies:doregister' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="exampleInputEmail1">用户名</label>
        <input type="text" class="form-control" name="username" placeholder="请输入用户名">
        <p class="help-block">请输入6-16位用户名</p>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">密码</label>
        <input type="password" class="form-control" name="userpassword" placeholder="请输入密码">
        <p class="help-block">请输入6位以上拼音字母组合密码</p>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">确认密码</label>
        <input type="password" class="form-control" placeholder="请再次输入密码">
        <p class="help-block">请再次输入6位以上拼音字母组合密码</p>
    </div>
      <div class="form-group">
        <label for="exampleInputPassword1">邮箱</label>
        <input type="text" name="useremail" class="form-control" placeholder="请输入邮箱">
        <p class="help-block">请输入邮箱包含@符号</p>
    </div>
    <div class="form-group">
        <label for="exampleInputFile">头像</label>
        <input type="file" name="usericon">

    </div>
    <div class="submit">
        <button type="submit" class="btn btn-primary">注册</button>
    </div>
    {#    <span>用户名:</span><input type="text" name="username" placeholder="请输入用户名">#}
    {#    <br>#}
    {#    <span>密码:</span><input type="password" name="userpassword" placeholder="请输入密码">#}
    {#    <br>#}
    {#    <span>确认密码:</span><input type="password" placeholder="请再次输入密码">#}
    {#    <br>#}
    {#    <span>邮箱:</span><input type="text" name="useremail" placeholder="请输入邮箱">#}
    {#    <br>#}
    {#    <span>头像:</span><input type="file" name="usericon" placeholder="请选择头像">#}
    {#    <br>#}
    {#    <input type="submit" value="注册">#}
</form>

</body>
</html>

templates/userinfo.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户信息修改</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <script type="text/javascript" src={% static 'amovies/js/jquery.js' %}></script>
    <script type="text/javascript" src={% static 'amovies/js/bootstrap.js' %}></script>
    <link rel="stylesheet" href="{% static 'amovies/css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/bootstrap-theme.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/swiper.css' %}"/>
    <script type="text/javascript" src="{% static 'amovies/js/swiper.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'amovies/css/reset.css' %}"/>
    <style type="text/css">
        .form-info {
            border: 1px solid orange;
            margin: 100px auto;
            width: 30%;
            padding: 50px;
        }

        .form-info h2 {
            font-size: 2rem;
            margin-bottom: 20px;
        }

        .form-info .submit {
            text-align: center;
        }

        .form-info img {
            width: 40px;
            height: 40px;
            float: left;
        }

        input[type=file] {
            float: left;
            height: 40px;
            line-height: 40px;
            padding-left: 20px;
        }
    </style>
</head>
<body>

<div class="container-fluid">
			<div class="form-info">

				<h2>信息修改</h2>

				<form action="{% url 'amovies:douserinfo' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
					<div class="form-group">
						<label for="exampleInputEmail1">用户名</label>
						<input type="text" class="form-control" id="exampleInputEmail1" placeholder="请输入用户名" value="Rock" disabled="disabled">
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">邮箱</label>
						<input type="email" name="email" class="form-control" placeholder="请输入新的邮箱" value="旧邮箱">
					</div>
					<div class="form-group clearfix">
						<label for="exampleInputFile">头像</label><br />
						<img class="img-circle" src="{{ usericon }}" alt="" />
						<input type="file" name="icon" id="exampleInputFile">
					</div>
					<div class="submit"><button type="submit" class="btn btn-primary">提交</button></div>

				</form>
			</div>
		</div>
</body>
</html>